Bnan.Ui/Areas/CAS/Controllers/CasReports/ReportSaved_CanceledContract_CasController.cs
using AutoMapper;
using Bnan.Core.Extensions;
using Bnan.Core.Interfaces;
using Bnan.Core.Interfaces.Base;
using Bnan.Core.Interfaces.MAS;
using Bnan.Core.Models;
using Bnan.Inferastructure.Filters;
//using Bnan.Inferastructure.Repository.CAS;
using Bnan.Ui.Areas.Base.Controllers;
using Bnan.Ui.Areas.CAS.Controllers;
using Bnan.Ui.ViewModels.CAS;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Azure;
using Microsoft.Extensions.Localization;
using NToastNotify;
using System.Numerics;
namespace Bnan.Ui.Areas.CAS.Controllers.CasReports
{
    [Area("CAS")]
    [Authorize(Roles = "CAS")]
    [ServiceFilter(typeof(SetCurrentPathCASFilter))]
    public class ReportSaved_CanceledContract_CasController : BaseController
    {
        private readonly IUserLoginsService _userLoginsService;
        private readonly IUserService _userService;
        private readonly IMasRenterInformation _masRenterInformation;
        private readonly IBaseRepo _baseRepo;
        private readonly IMasBase _masBase;
        private readonly IToastNotification _toastNotification;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IStringLocalizer<ReportSaved_CanceledContract_CasController> _localizer;
        private readonly string pageNumber = SubTasks.SavedAndCanceled_contracts_Report_Cas;


        public ReportSaved_CanceledContract_CasController(UserManager<CrMasUserInformation> userManager, IUnitOfWork unitOfWork,
            IMapper mapper, IUserService userService, IMasRenterInformation masRenterInformation, IBaseRepo BaseRepo, IMasBase masBase,
            IUserLoginsService userLoginsService, IToastNotification toastNotification, IWebHostEnvironment webHostEnvironment, IStringLocalizer<ReportSaved_CanceledContract_CasController> localizer) : base(userManager, unitOfWork, mapper)
        {
            _userService = userService;
            _masRenterInformation = masRenterInformation;
            _userLoginsService = userLoginsService;
            _baseRepo = BaseRepo;
            _masBase = masBase;
            _toastNotification = toastNotification;
            _webHostEnvironment = webHostEnvironment;
            _localizer = localizer;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {


            // Set page titles
            var user = await _userManager.GetUserAsync(User);
            await SetPageTitleAsync(string.Empty, pageNumber);
            // Check Validition
            if (!await _baseRepo.CheckValidation(user.CrMasUserInformationCode, pageNumber, Status.ViewInformation))
            {
                _toastNotification.AddErrorToastMessage(_localizer["AuthEmplpoyee_No_auth"], new ToastrOptions { PositionClass = _localizer["toastPostion"], Title = "", }); //  إلغاء العنوان الجزء العلوي
                return RedirectToAction("Index", "Home");
            }

            var listmaxDate = await _unitOfWork.CrCasRenterContractBasic.FindAllWithSelectAsNoTrackingAsync(
                    predicate: x => x.CrCasRenterContractBasicStatus == Status.Update || x.CrCasRenterContractBasicStatus == Status.Cancel,
                    selectProjection: query => query.Select(x => new Date_ReportSaved_CanceledContract_CasVM
                    {
                        dates = x.CrCasRenterContractBasicExpectedStartDate,
                    }));

            if (listmaxDate?.Count == 0 )
            {
                _toastNotification.AddErrorToastMessage(_localizer["NoDataToShow"], new ToastrOptions { PositionClass = _localizer["toastPostion"], Title = "", }); //  إلغاء العنوان الجزء العلوي
                return RedirectToAction("Index", "Home");
            }

            var maxDate = listmaxDate.Max(x => x.dates)?.ToString("yyyy-MM-dd");

            var end = DateTime.Now.AddDays(1);
            var start = DateTime.Now.AddMonths(-1);
            if (maxDate != null)
            {
                end = DateTime.Parse(maxDate).AddDays(1);
                start = DateTime.Parse(maxDate).AddMonths(-1);
            }

            var all_RenterBasicContract = await _unitOfWork.CrCasRenterContractBasic.FindAllWithSelectAsNoTrackingAsync(
                //predicate: x => x.CrCasCarInformationStatus != Status.Deleted,
                predicate: x => (x.CrCasRenterContractBasicStatus == Status.Update || x.CrCasRenterContractBasicStatus == Status.Cancel)
                && x.CrCasRenterContractBasicLessor == user.CrMasUserInformationLessor
                && x.CrCasRenterContractBasicExpectedStartDate > start && x.CrCasRenterContractBasicExpectedStartDate <= end,
                selectProjection: query => query.Select(x => new ReportSaved_CanceledContract_CasVM
                {
                    CrCasRenterContractBasicNo = x.CrCasRenterContractBasicNo,
                    CrCasRenterContractBasicCopy = x.CrCasRenterContractBasicCopy,
                    CrCasRenterContractBasicLessor = x.CrCasRenterContractBasicLessor,
                    CrCasRenterContractBasicRenterId = x.CrCasRenterContractBasicRenterId,
                    CrCasRenterContractBasicCarSerailNo = x.CrCasRenterContractBasicCarSerailNo,
                    CrCasRenterContractBasicExpectedStartDate = x.CrCasRenterContractBasicExpectedStartDate,
                    //CrCasRenterContractBasicActualCloseDateTime = x.CrCasRenterContractBasicActualCloseDateTime,
                    CrCasRenterContractBasicPdfFile = x.CrCasRenterContractBasicPdfFile,
                    CrCasRenterContractBasicPdfTga = x.CrCasRenterContractBasicPdfTga,
                    CarArName = x.CrCasRenterContractBasicCarSerailNoNavigation.CrCasCarInformationConcatenateArName,
                    CarEnName = x.CrCasRenterContractBasicCarSerailNoNavigation.CrCasCarInformationConcatenateEnName,
                    CrCasRenterContractBasicExpectedEndDate = x.CrCasRenterContractBasicExpectedEndDate,
                    CrCasRenterContractBasicStatus = x.CrCasRenterContractBasicStatus,
                    CrCasRenterContractBasicExpectedRentalDays = x.CrCasRenterContractBasicExpectedRentalDays,
                    CrCasRenterContractBasicExpectedTotal = x.CrCasRenterContractBasicExpectedTotal,
                    CrCasRenterContractBasicAmountPaidAdvance = x.CrCasRenterContractBasicAmountPaidAdvance,
                    branchAr = x.CrCasRenterContractBasic1.CrCasBranchInformationArShortName,
                    branchEn = x.CrCasRenterContractBasic1.CrCasBranchInformationEnShortName,
                })
                , includes: new string[] { "CrCasRenterContractBasicCarSerailNoNavigation", "CrCasRenterContractBasic1" }
                );
            var allRenters = await _unitOfWork.CrMasRenterInformation.FindAllWithSelectAsNoTrackingAsync(
                predicate: x => x.CrMasRenterInformationStatus != Status.Deleted,
                selectProjection: query => query.Select(x => new CrMasRenterInformation
                {
                    CrMasRenterInformationId = x.CrMasRenterInformationId,
                    CrMasRenterInformationArName = x.CrMasRenterInformationArName,
                    CrMasRenterInformationEnName = x.CrMasRenterInformationEnName,
                    CrMasRenterInformationStatus = x.CrMasRenterInformationStatus,
                })
                //,includes: new string[] { "CrMasRenterInformationNationalityNavigation", "CrMasRenterInformationProfessionNavigation" } 
                );


            var all_Invoices = await _unitOfWork.CrCasAccountInvoice.FindAllWithSelectAsNoTrackingAsync(
                 //predicate: x => x.CrCasCarInformationStatus != Status.Deleted,
                 predicate: null,
                 selectProjection: query => query.Select(x => new cas_list_String_4
                 {
                     id_key = x.CrCasAccountInvoiceReferenceContract,
                     nameAr = x.CrCasAccountInvoicePdfFile,
                     str4 = x.CrCasAccountInvoiceUserCode,
                 })
                 //,includes: new string[] { "" } 
                 );

            listReportSaved_CanceledContract_CasVM VM = new listReportSaved_CanceledContract_CasVM();
            VM.all_RentersMas = allRenters;
            VM.all_contractBasic = all_RenterBasicContract;
            VM.all_Invoices = all_Invoices;
            VM.start_Date = start.ToString("yyyy-MM-dd");
            VM.end_Date = end.AddDays(-1).ToString("yyyy-MM-dd");

            return View(VM);
        }

        [HttpGet]
        [Route("/CAS/ReportSaved_CanceledContract_Cas/GetContractsByStatus")]
        public async Task<PartialViewResult> GetContractsByStatus(string status,string start , string end)
        {
            var user = await _userManager.GetUserAsync(User);

            //sidebar Active
            if (start == "undefined-undefined-") start = "";
            if (end == "undefined-undefined-") end = "";
            if (string.IsNullOrEmpty(start) && string.IsNullOrEmpty(end))
            {
                start = DateTime.Now.AddMonths(-1).ToString("dd-MM-yyyy");
                end = DateTime.Now.ToString("dd-MM-yyyy");
            }
            if (!string.IsNullOrEmpty(status) && !string.IsNullOrEmpty(start) && !string.IsNullOrEmpty(end))
            {
                var start_Date = DateTime.Parse(start);
                var end_Date = DateTime.Parse(end).AddDays(1);
                
                var AllContracts = await _unitOfWork.CrCasRenterContractBasic.FindAllWithSelectAsNoTrackingAsync(
                    //predicate: x => x.CrCasCarInformationStatus != Status.Deleted,
                    predicate: x => (x.CrCasRenterContractBasicStatus == Status.Update || x.CrCasRenterContractBasicStatus == Status.Cancel)
                    && x.CrCasRenterContractBasicLessor == user.CrMasUserInformationLessor

Bnan.Ui/Areas/CAS/Views/ReportSaved_CanceledContract_Cas/Index.cshtml
@using Bnan.Core.Extensions
@using Bnan.Ui.ViewModels.CAS;
@* @model IEnumerable<CrMasRenterInformation>
*@
@model listReportSaved_CanceledContract_CasVM
@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> options
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
       ViewData["returnUrl"] = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}"; 
    ViewData["Page-title"] = @localizer["RenterInformations Data"];
    ViewData["Page-Hint"] = @localizer["RenterInformations Hint"];
}


@*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">*@

<div class="col d-flex align-items-center justify-content-center" style=" z-index:2;">
    <div class="container main-container">
        <form action="">
            <div class="row g-3 mb-3">
                <div class="col">
                    <h3>@localizer["ReportSaved_CanceledContract_Data"]</h3>
                </div>
                    <div class="row g-2">

                        <div class="col-lg-8">
                            <div class="col-12 d-flex align-items-center Search-col  flex-wrap gap-2">
                                <div class="col-xl-4 d-flex  gap-3 align-items-center">
                                    <label for="start_date">@localizer["From_n"]</label>
                                    <input type="date" class="form-control inputs custom-date-input" id="start_date" name="start_date" required>
                                </div>
                                <div class="col-xl-4 d-flex  gap-3 align-items-center">
                                    <label for="end_date">@localizer["To_n"]</label>
                                    <input type="date" class="form-control inputs custom-date-input" id="end_date" name="end_date" required>
                                    @*<input type="text" class="form-control inputs custom-date-input" id="end_date" name="end_date" required="" autocomplete="off">*@

                                </div>

                                <button type="button" id="btn_view" name="btn_view" class="btn btn-standard">@localizer["View_n"]</button>
                            </div>
                        </div>
                        <div class="col-md-8 col-lg-4 search-input-col">
                            <div class="form-outline w-100" data-mdb-input-init>
                                <span class="fa fa-search"></span>
                                <input type="search" id="search2" class="form-control inputs search-input" aria-label="Search" autofocus autocomplete="off" />
                            </div>
                        </div>
                        <div class="col-12 filters-col">
                            <div class="filters-custom-order">

                                <label class="form-check-label" for="All">@localizer["All_n"]</label>
                                <input class="form-check-input custom" type="radio" name="customRadio" id="All"
                                       value="All" checked />
                            </div>
                            <div class="filters-custom-order">

                                <label class="form-check-label filter2" for="@Status.Update">@localizer["Saved_status_n"]</label>
                                <input class="form-check-input custom" type="radio" name="customRadio" id="@Status.Update"
                                       value="@Status.Update" />
                            </div>

                            <div class="filters-custom-order">

                                <label class="form-check-label  filter3" for="@Status.Cancel">@localizer["Canceled_status_n"]</label>
                                <input class="form-check-input custom" type="radio" name="customRadio" id="@Status.Cancel"
                                       value="@Status.Cancel" />
                            </div>
                        </div>
                </div>
            </div>

            <div class="row table-row px-3">
                <div class="col  scroll-table-div filter-search-reportTable table-responsive-sm w-100 dataTable">
                    <partial name="_DataTableReportSaved_CanceledContract_Cas" />
                </div>
            </div>
        </form>
            <a asp-area="CAS" asp-controller="Home" asp-action="Index" data-bs-toggle="tooltip" data-bs-placement="top"
           data-bs-custom-class="custom-tooltip" data-bs-title="@localizer["BackToHome"]" class="new-Page-icon">
            <img src="~/MasSystem/images/back to main.svg" alt="man">
        </a>
    </div>
    </div>
@*////////////////////////////*@@*////////////////////////////*@@*////////////////////////////*@
@*////////////////////////////*@@*////////////////////////////*@@*////////////////////////////*@


    @section Scripts{
    <!-- تحميل مكتبة jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- تحميل مكتبة DataTables -->
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

    @*    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
    // تهيئة flatpickr مع التنسيق المطلوب
    flatpickr("#start_date", {
        dateFormat: "d/m/Y", // تنسيق التاريخ إلى يوم/شهر/سنة
    });
        // تهيئة flatpickr مع التنسيق المطلوب
    flatpickr("#end_date", {
        dateFormat: "d/m/Y", // تنسيق التاريخ إلى يوم/شهر/سنة
    });
</script>*@

    <script>
        $(document).ready(function () {
            $("#start_date").val('@Model.start_Date'); //  اضافة قيمة البداية من ال viewModel
            $("#end_date").val('@Model.end_Date'); //  اضافة قيمة النهاية من ال viewModel

            // لجعل الحالة حسب ما هي جاية من index نشط او الكل
            $("#min-loader").toggleClass("d-none", true); // اخفاء loader بعد انتهاء تحميل الصفحة

            //var today = new Date();
            //$("#start_date").datepicker({
            //    dateFormat: 'yy/mm/dd',  // التاريخ إلى يوم/شهر/سنة
            //    maxDate: today,
            //});
            //$("#end_date").datepicker({
            //    dateFormat: 'yy/mm/dd',  // التاريخ إلى يوم/شهر/سنة
            //    maxDate: today,
            //});

            // Close modal when close button is clicked
            $('.close').click(function () {
                $('#DataModal').modal('hide');
            });

            ///////
            // تهيئة DataTable
            var table2 = $('#Table').DataTable({
                ordering: false, // تعطيل الترتيب التلقائي للصفوف
                stateSave: true,   // حفظ حالة الجدول
            });
            end_init_ShowDatatable();
        });

        function end_init_ShowDatatable() {
            $("#min-loader").toggleClass("d-none", true);
            $("select[name='Table_length']").prepend("<option value='10000' id='A10000'>10000</option>");
            //$("select[name='Table_length'] option[value='10000']").prop("selected", true);
            $("select[name='Table_length']").val('10000').change();
            $("#Table_info").css("display", "none");
            $("#Table_previous").css("display", "none");
            $("#Table_next").css("display", "none");
            $("#Table_length").css("display", "none");
            $("#Table_filter").css("display", "none");
            $(".paginate_button").css("display", "none");
            $(".ellipsis").css("display", "none");
            $("select[name='Table_length'] option[value='10000']").prop("selected", true);
        }

        // دالة للبحث عن كلمة في جميع الصفوف
        function searchRows() {
            $("#min-loader").removeClass("d-none");// اظهار loader تحميل

            var table = $('#Table').DataTable();
            end_init_ShowDatatable();
            var keyword = $('#search2').val().toLowerCase(); // الكلمة المدخلة للبحث (تحويلها إلى حروف صغيرة)


            // إخفاء كل الصفوف أولاً
            table.rows().every(function () {
                this.nodes().to$().hide(); // إخفاء الصف
            });

            // التكرار عبر كل الصفوف
            table.rows().every(function () {
                var row = this.data();
                var found = false;

                // التكرار عبر كل الخلايا في الصف
                row.forEach(function (cell) {
                    if (cell.toString().toLowerCase().includes(keyword)) {
                        found = true; // إذا تم العثور على الكلمة في أي خلية
                    }
                });

                // إذا تم العثور على الكلمة في الصف، نظهره
                if (found) {
                    this.nodes().to$().show();                  
                }
            });

           
            $("#min-loader").toggleClass("d-none", true); // اخفاء loader بعد انتهاء تحميل الصفحة
            //$("select[name='Table_length']").prepend("<option value='10000' id='A10000'>10000</option>");
        }


        // يمكن إضافة وظيفة البحث تلقائيًا عند كتابة النص
        $('#search2').on('keyup', function () {
            searchRows();
        });

    </script>
    <script>
        //get ReportSaved_CanceledContract_Cas By Status function
        function GetContractsByStatusFitler(status, start, end) {
            $.ajax({
                type: "GET",
                data: {
                    status: status, start: start, end: end
                },
                url: "@Url.Action("GetContractsByStatus", "ReportSaved_CanceledContract_Cas", new { Area = "CAS" })",
                success: function (response) {
                    $(".dataTable").html(response);
                    var table3 = $('#Table').DataTable();
                    end_init_ShowDatatable();
                    $("#min-loader").toggleClass("d-none", true);
                },
            })
        }

        $("input[name='customRadio']").on("click", function () {
            const start = $("#start_date").val(); // الحصول على قيمة البداية
            const end = $("#end_date").val(); // الحصول على قيمة النهاية
            const status = $(this).val();
            
            $("#min-loader").removeClass("d-none");
            $("#search2").val("");
            GetContractsByStatusFitler(status, start, end);
        });

        // عند كتابة أي شيء في حقل البحث، تحديث الفلتر
        $("#btn_view").on("click", function () {
            const start = $("#start_date").val(); // الحصول على قيمة البداية
            const end = $("#end_date").val(); // الحصول على قيمة النهاية
            const status = $("input[name='customRadio']:checked").val(); // الحصول على القيمة المحددة من الراديو

            
            $("#min-loader").removeClass("d-none");
            $("#search2").val("");
            GetContractsByStatusFitler(status,start, end);
        });
    </script>
}

Bnan.Ui/Areas/CAS/Views/ReportSaved_CanceledContract_Cas/_DataTableReportSaved_CanceledContract_Cas.cshtml
@using Bnan.Core.Extensions
@using Bnan.Ui.ViewModels.CAS;
@model listReportSaved_CanceledContract_CasVM
@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> options
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    ViewData["returnUrl"] = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}


<table class=" tables-style table table-borderless " id="Table">
    <thead class="sticky-top">
        <tr>
@*            <th>@localizer["the_TGA_n"]</th>
            <th>@localizer["the_Contract_n"]</th>*@
            <th>@localizer["the_Invoice_n"]</th>
            <th> @localizer["Paid_Value_n"]</th>
            <th> @localizer["expectedValue_n"]</th>
            <th> @localizer["Closed_contract_DayCount"]</th>
            <th class="DifferAlign"> @localizer["the_Car_and_Renter"]</th>
            <th class="DifferAlign"> @localizer["Exist_contract_Branch"]  </th>
            <th class="DifferAlign">@localizer["the_Contract_n"]</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            var no = 1;
        }
        @foreach (var item in Model.all_contractBasic)
        {

            var endDate = item.CrCasRenterContractBasicExpectedEndDate;
           @* var Contract_pdf = "#";
            var Contract_pdf_blank = "";
           *@ var Invoice_pdf = "#";
            var Invoice_pdf_blank = "";
            @*var TGA_pdf = "#";
            var TGA_pdf_blank = "";
           *@var invoce_ar = Model.all_Invoices?.Find(x => x.id_key == item.CrCasRenterContractBasicNo)?.nameAr ?? "";
            var invoce_en = Model.all_Invoices?.Find(x => x.id_key == item.CrCasRenterContractBasicNo)?.nameEn ?? "";
            @*if (item.CrCasRenterContractBasicPdfFile != null && item.CrCasRenterContractBasicPdfFile != "") { Contract_pdf = item.CrCasRenterContractBasicPdfFile?.ToString().Replace("~", ""); Contract_pdf_blank = "_blank"; }
              if (item.CrCasRenterContractBasicPdfTga != null && item.CrCasRenterContractBasicPdfTga != "") { TGA_pdf = item.CrCasRenterContractBasicPdfTga?.ToString().Replace("~", ""); TGA_pdf_blank = "_blank"; }
            *@
            if (requestCulture?.RequestCulture.UICulture.Name == "en-US")
            {
                if (invoce_en != null && invoce_en != "") { Invoice_pdf = invoce_en?.ToString().Replace("~", ""); Invoice_pdf_blank = "_blank"; }
            }
            else
            {
                if (invoce_ar != null && invoce_ar != "") { Invoice_pdf = invoce_ar?.ToString().Replace("~", ""); Invoice_pdf_blank = "_blank"; }

            }


            <tr>
@*                <td><a href="@TGA_pdf" target="@TGA_pdf_blank"><img class="pdf-Tableicons" src="~/CasSys/images/naql.svg"></a></td>
                <td><a href="@Contract_pdf" target="@Contract_pdf_blank"><img class="pdf-Tableicons" src="~/CasSys/images/contract.svg"></a></td>*@
                <td><a href="@Invoice_pdf" target="@Invoice_pdf_blank"><img class="pdf-Tableicons" src="~/CasSys/images/Invoice.svg"></a></td>

                <td><p>@item.CrCasRenterContractBasicAmountPaidAdvance?.ToString("N2",CultureInfo.InvariantCulture)</p></td>
                <td><p>@item.CrCasRenterContractBasicExpectedTotal?.ToString("N2",CultureInfo.InvariantCulture)</p></td>
                <td><p>@item.CrCasRenterContractBasicExpectedRentalDays</p></td>

                @if (requestCulture?.RequestCulture.UICulture.Name == "en-US")
                {

                    <td class="DifferAlign">
                        <p class="FirstLineP">@Model.all_RentersMas?.Find(x=>x.CrMasRenterInformationId == item.CrCasRenterContractBasicRenterId)?.CrMasRenterInformationEnName</p>
                        <div class="car-name-color">
                            <p class="FirstLineP">@item.CarEnName</p>
                            <div class="CarColor" style="background: #636C14;"></div>
                        </div>
                    </td>

                    <td class="DifferAlign"><p> @item.branchEn </p></td>
                    <td class="DifferAlign">
                        @if (item.CrCasRenterContractBasicCopy > 0)
                        {
                            <p class="FirstLineP"> <span style="color:red">(@item.CrCasRenterContractBasicCopy)</span>  @item.CrCasRenterContractBasicNo </p>
                        }
                        else
                        {
                            <p class="FirstLineP"> @item.CrCasRenterContractBasicNo </p>
                        }
                        <div class="d-flex justify-content-end gap-1">
                            <p class="secondLineP"> <span class="time">  @endDate?.ToString("HH:mm ",CultureInfo.InvariantCulture) </span> @endDate?.ToString("dd/MM/yyyy ",CultureInfo.InvariantCulture) </p>
                            <p class="secondLineP"> <span class="time">  @item.CrCasRenterContractBasicExpectedStartDate?.ToString("HH:mm ",CultureInfo.InvariantCulture) </span> @item.CrCasRenterContractBasicExpectedStartDate?.ToString("dd/MM/yyyy ",CultureInfo.InvariantCulture)</p>
                        </div>
                    </td>
                }
                else
                {
                    <td class="DifferAlign">
                        <p class="FirstLineP">@Model.all_RentersMas?.Find(x=>x.CrMasRenterInformationId == item.CrCasRenterContractBasicRenterId)?.CrMasRenterInformationArName</p>
                        <div class="car-name-color">
                            <p class="FirstLineP">@item.CarArName</p>
                            <div class="CarColor" style="background: #636C14;"></div>
                        </div>
                    </td>
                    <td class="DifferAlign"><p> @item.branchAr </p></td>
                    <td class="DifferAlign">
                        @if (item.CrCasRenterContractBasicCopy > 0)
                        {
                            <p class="FirstLineP"> <span style="color:red">(@item.CrCasRenterContractBasicCopy)</span>  @item.CrCasRenterContractBasicNo </p>
                        }
                        else
                        {
                            <p class="FirstLineP"> @item.CrCasRenterContractBasicNo </p>
                        }
                        <div class="d-flex justify-content-end gap-1">
                            <p class="secondLineP">@item.CrCasRenterContractBasicExpectedStartDate?.ToString("dd/MM/yyyy ",CultureInfo.InvariantCulture) <span class="time">  @item.CrCasRenterContractBasicExpectedStartDate?.ToString(" HH:mm",CultureInfo.InvariantCulture) </span></p>
                            <p class="secondLineP">@endDate?.ToString("dd/MM/yyyy ",CultureInfo.InvariantCulture) <span class="time"> @endDate?.ToString(" HH:mm",CultureInfo.InvariantCulture) </span></p>
                        </div>
                    </td>
                }
                <td>
                    <div class="filter-number-td">
                        @{
                            var filterColor = "";
                            var filterStyleColor = "";
                            if (item.CrCasRenterContractBasicStatus == Status.Cancel) filterColor = "filter3-div";
                            else if (item.CrCasRenterContractBasicStatus == Status.Update) filterColor = "filter2-div";
                        }
                        <div class="filters @filterColor" style="@filterStyleColor"></div>
                        <div>@no</div>
                    </div>
                </td>
            </tr>
            no++;
        }

    </tbody>

</table>