Bnan.Ui/Areas/CAS/Controllers/Renters/RenterContractController.cs
using AutoMapper;
using Bnan.Core.Extensions;
using Bnan.Core.Interfaces;
using Bnan.Core.Interfaces.Base;
using Bnan.Core.Interfaces.CAS;
using Bnan.Core.Interfaces.MAS;
using Bnan.Core.Models;
using Bnan.Inferastructure.Filters;
using Bnan.Inferastructure.Repository.CAS;
using Bnan.Ui.Areas.Base.Controllers;
using Bnan.Ui.Areas.CAS.Controllers;
using Bnan.Ui.ViewModels.CAS;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Azure;
using Microsoft.Extensions.Localization;
using NToastNotify;
using System.Numerics;
using Bnan.Ui.ViewModels.CAS.Renters;

namespace Bnan.Ui.Areas.CAS.Controllers.Renters
{
    [Area("CAS")]
    [Authorize(Roles = "CAS")]
    [ServiceFilter(typeof(SetCurrentPathCASFilter))]
    public class RenterContractController : BaseController
    {
        private readonly IUserLoginsService _userLoginsService;
        private readonly IUserService _userService;
        private readonly IBaseRepo _baseRepo;
        private readonly IMasBase _masBase;
        private readonly IToastNotification _toastNotification;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IStringLocalizer<RenterContractController> _localizer;
        private readonly string pageNumber = SubTasks.RentersCas_RentersContracts;


        public RenterContractController(UserManager<CrMasUserInformation> userManager, IUnitOfWork unitOfWork,
            IMapper mapper, IUserService userService,  IBaseRepo BaseRepo, IMasBase masBase,
            IUserLoginsService userLoginsService, IToastNotification toastNotification, IWebHostEnvironment webHostEnvironment, IStringLocalizer<RenterContractController> localizer) : base(userManager, unitOfWork, mapper)
        {
            _userService = userService;
            _userLoginsService = userLoginsService;
            _baseRepo = BaseRepo;
            _masBase = masBase;
            _toastNotification = toastNotification;
            _webHostEnvironment = webHostEnvironment;
            _localizer = localizer;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {


            // Set page titles
            var user = await _userManager.GetUserAsync(User);
            await SetPageTitleAsync(string.Empty, pageNumber);
            // Check Validition
            if (!await _baseRepo.CheckValidation(user.CrMasUserInformationCode, pageNumber, Status.ViewInformation))
            {
                _toastNotification.AddErrorToastMessage(_localizer["AuthEmplpoyee_No_auth"], new ToastrOptions { PositionClass = _localizer["toastPostion"], Title = "", }); //  إلغاء العنوان الجزء العلوي
                return RedirectToAction("Index", "Home");
            }


            var allRenters = await _unitOfWork.CrMasRenterInformation.FindAllWithSelectAsNoTrackingAsync(
                //predicate: x => x.CrCasCarInformationStatus != Status.Deleted,
                predicate: null,
                selectProjection: query => query.Select(x => new CrMasRenterInformation
                {
                    CrMasRenterInformationId = x.CrMasRenterInformationId,
                    CrMasRenterInformationArName = x.CrMasRenterInformationArName,
                    CrMasRenterInformationEnName = x.CrMasRenterInformationEnName,
                    CrMasRenterInformationStatus = x.CrMasRenterInformationStatus,
                })
                //,includes: new string[] { "CrMasRenterInformationNationalityNavigation", "CrMasRenterInformationProfessionNavigation" } 
                );

            var allCasRenterLessor = await _unitOfWork.CrCasRenterLessor.FindAllWithSelectAsNoTrackingAsync(
                predicate: x=>x.CrCasRenterLessorCode== user.CrMasUserInformationLessor && x.CrCasRenterLessorStatus!=Status.Deleted,
                selectProjection: query => query.Select(x => new CrCasRenterLessor
                {
                    CrCasRenterLessorId = x.CrCasRenterLessorId,
                    CrCasRenterLessorDateFirstInteraction = x.CrCasRenterLessorDateFirstInteraction,
                    CrCasRenterLessorDateLastContractual = x.CrCasRenterLessorDateLastContractual,
                    CrCasRenterLessorContractCount = x.CrCasRenterLessorContractCount,
                    CrCasRenterLessorContractDays = x.CrCasRenterLessorContractDays,
                    CrCasRenterLessorContractKm = x.CrCasRenterLessorContractKm,
                    CrCasRenterLessorStatus = x.CrCasRenterLessorStatus,
                })
                );
            var allCasRenterIds = await _unitOfWork.CrCasRenterLessor.FindAllWithSelectAsNoTrackingAsync(
                predicate: x => x.CrCasRenterLessorCode == user.CrMasUserInformationLessor && x.CrCasRenterLessorStatus != Status.Deleted,
                selectProjection: query => query.Select(x => new CrCasRenterLessor
                {
                    CrCasRenterLessorId = x.CrCasRenterLessorId,
                })
                );
            allCasRenterIds = allCasRenterIds?.DistinctBy(x => x.CrCasRenterLessorId)?.ToList();
            // If no active licenses, retrieve all licenses
            if (!allRenters.Any())
            {
                ViewBag.radio = "All";
            }
            else ViewBag.radio = "A";
            if (allCasRenterIds?.Count == 0 || allRenters.Count == 0)
            {
                _toastNotification.AddErrorToastMessage(_localizer["NoDataToShow"], new ToastrOptions { PositionClass = _localizer["toastPostion"], Title = "", }); //  إلغاء العنوان الجزء العلوي
                return RedirectToAction("Index", "Home");
            }
            RenterContractVM VM = new RenterContractVM();
            VM.all_Renters = allRenters;
            VM.allCasRenterLessor = allCasRenterLessor;
            VM.allCasRenterIds = allCasRenterIds;


            return View(VM);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.GetUserAsync(User);

            listRenterContractVM VM = new listRenterContractVM();

            await SetPageTitleAsync(Status.Update, pageNumber);
            var thisRenterBasicContract = await _unitOfWork.CrCasRenterContractBasic.FindAllWithSelectAsNoTrackingAsync(
                //predicate: x => x.CrCasCarInformationStatus != Status.Deleted,
                predicate: x => x.CrCasRenterContractBasicRenterId == id && x.CrCasRenterContractBasicLessor == user.CrMasUserInformationLessor
                && (x.CrCasRenterContractBasicStatus == Status.Active || x.CrCasRenterContractBasicStatus == Status.Closed || x.CrCasRenterContractBasicStatus == Status.Expire)
                ,
                selectProjection: query => query.Select(x => new RenterContractVM
                {
                    CrCasRenterContractBasicNo = x.CrCasRenterContractBasicNo,
                    CrCasRenterContractBasicCopy = x.CrCasRenterContractBasicCopy,
                    CrCasRenterContractBasicLessor = x.CrCasRenterContractBasicLessor,
                    CrCasRenterContractBasicRenterId = x.CrCasRenterContractBasicRenterId,
                    CrCasRenterContractBasicBranch = x.CrCasRenterContractBasicBranch,
                    CrCasRenterContractBasicCarSerailNo = x.CrCasRenterContractBasicCarSerailNo,
                    CrCasRenterContractBasicCurrentReadingMeter = x.CrCasRenterContractBasicCurrentReadingMeter,
                    CrCasRenterContractBasicActualCurrentReadingMeter = x.CrCasRenterContractBasicActualCurrentReadingMeter,
                    CrCasRenterContractBasicExpectedStartDate = x.CrCasRenterContractBasicExpectedStartDate,
                    CrCasRenterContractBasicActualCloseDateTime = x.CrCasRenterContractBasicActualCloseDateTime,
                    CrCasRenterContractBasicActualDays = x.CrCasRenterContractBasicActualDays,
                    CrCasRenterContractBasicActualTotal = x.CrCasRenterContractBasicActualTotal,
                    CrCasRenterContractBasicPdfFile = x.CrCasRenterContractBasicPdfFile,
                    CrCasRenterContractBasicPdfTga = x.CrCasRenterContractBasicPdfTga,
                    CarArName = x.CrCasRenterContractBasicCarSerailNoNavigation.CrCasCarInformationPlateArNo,
                    CarEnName = x.CrCasRenterContractBasicCarSerailNoNavigation.CrCasCarInformationPlateEnNo,
                    CrCasRenterContractBasicExpectedEndDate = x.CrCasRenterContractBasicExpectedEndDate,
                    CrCasRenterContractBasicExpectedTotal = x.CrCasRenterContractBasicExpectedTotal,
                    CrCasRenterContractBasicExpectedRentalDays = x.CrCasRenterContractBasicExpectedRentalDays,
                    CrCasRenterContractBasicStatus = x.CrCasRenterContractBasicStatus,
                })
                , includes: new string[] { "CrCasRenterContractBasicCarSerailNoNavigation" }
                ); ;
            var ThisRenterData = await _unitOfWork.CrMasRenterInformation.FindAllWithSelectAsNoTrackingAsync(
                //predicate: x => x.CrCasCarInformationStatus != Status.Deleted,
                predicate: x => x.CrMasRenterInformationId == id,
                selectProjection: query => query.Select(x => new CrMasRenterInformation
                {
                    CrMasRenterInformationId = x.CrMasRenterInformationId,
                    CrMasRenterInformationArName = x.CrMasRenterInformationArName,
                    CrMasRenterInformationEnName = x.CrMasRenterInformationEnName,
                })
                //,includes: new string[] { "" } 
                );

            var all_Branches = await _unitOfWork.CrCasBranchInformation.FindAllWithSelectAsNoTrackingAsync(
                predicate: null,
                selectProjection: query => query.Select(x => new cas_list_String_4
                {
                    id_key = x.CrCasBranchInformationCode,

Bnan.Ui/Areas/MAS/Views/RenterContract/Index.cshtml
@using Bnan.Core.Extensions
@using Bnan.Ui.ViewModels.MAS
@* @model IEnumerable<CrMasRenterInformation>
*@
@model RenterContractVM
@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> options
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
       ViewData["returnUrl"] = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}"; 
    ViewData["Page-title"] = @localizer["RenterInformations Data"];
    ViewData["Page-Hint"] = @localizer["RenterInformations Hint"];
}

    <div class="col my-2 d-flex align-items-center justify-content-center" style="z-index: 2;">
    <div class="container main-container">
        <form action="">
            <div class="row g-3 mb-4">
                <div class="col">
                        <h3>@localizer["RenterContract_Data"]</h3>
                </div>
                <div class="col-12 col-lg-6 d-flex justify-content-end">

                    <div class="col-12 col-md-8 search-input-col">
                        <div class="form-outline w-100" data-mdb-input-init>
                            <span class="fa fa-search"></span>
                            <input type="search" id="search2" class="form-control inputs search-input"
                                   name="search" aria-label="Search" autofocus autocomplete="off" />
                        </div>
                    </div>

                </div>
            </div>

            <div class="row table-row px-3">
                <div class="col  scroll-table-div  table-responsive-sm w-100 dataTable">
                    <partial name="_DataTableRenterContract" />
                </div>
            </div>
        </form>
            <a asp-area="CAS" asp-controller="Home" asp-action="Index" data-bs-toggle="tooltip" data-bs-placement="top"
            data-bs-custom-class="custom-tooltip" data-bs-title="@localizer["BackToHome"]" class="new-Page-icon">
            <img src="~/MasSystem/images/back to main.svg" alt="man">
        </a>
    </div>
</div>

    @section Scripts{
    <!-- تحميل مكتبة jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- تحميل مكتبة DataTables -->
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>



@*<script>
    document.addEventListener("DOMContentLoaded", function () {
        var table = document.getElementById("Table");
        var rows = table.getElementsByTagName("tr");

        for (var i = 0; i < rows.length; i++) {
            var cells = rows[i].getElementsByTagName("td");

            for (var j = 0; j < cells.length; j++) {
                cells[j].addEventListener("click", function () {
                    window.location.href = "DetaildData.html";
                });
            }
        }
    });
</script>*@
@*<script>
        function GetRenterIdtypeFitler(search) {
            $.ajax({
                type: "GET",
                data: {
                    search: search
                },
                url: "@Url.Action("GetRenterIdtypeByStatus", "RenterContract", new { Area = "MAS" })",
                success: function (response) {
                    $(".dataTable").html(response);
                },
            })
        }
        // عند كتابة أي شيء في حقل البحث، تحديث الفلتر
        $("#search").on("change", function () {
            const search = $(this).val(); // الحصول على قيمة البحث
            GetRenterIdtypeFitler(search);
        });
    async function getSearch(){
           var search1 = $('search').val();
    }
</script>*@
<script>
        $(document).ready(function () {
            $("#min-loader").removeClass("d-none") // تشغيل لودر
            // تهيئة DataTable
            var table = $('#Table').DataTable({
                ordering: false, // تعطيل الترتيب التلقائي للصفوف
                stateSave: true,   // حفظ حالة الجدول
            });

            $("select[name='Table_length']").prepend("<option value='10000' id='A10000'>10000</option>");
            //$("select[name='Table_length'] option[value='10000']").prop("selected", true);
            $("select[name='Table_length']").val('10000').change();
            $("#Table_info").css("display", "none");
            $("#Table_previous").css("display", "none");
            $("#Table_next").css("display", "none");
            $("#Table_length").css("display", "none");
            $("#Table_filter").css("display", "none");
            $(".paginate_button").css("display", "none");
            $(".ellipsis").css("display", "none");
            $("#min-loader").toggleClass("d-none", true);

            // دالة للبحث عن كلمة في جميع الصفوف
            function searchRows() {
                var keyword = $('#search2').val().toLowerCase(); // الكلمة المدخلة للبحث (تحويلها إلى حروف صغيرة)

                // إخفاء كل الصفوف أولاً
                table.rows().every(function () {
                    this.nodes().to$().hide(); // إخفاء الصف
                });

                // التكرار عبر كل الصفوف
                table.rows().every(function () {
                    var row = this.data();
                    var found = false;

                    // التكرار عبر كل الخلايا في الصف
                    row.forEach(function (cell) {
                        if (cell.toString().toLowerCase().includes(keyword)) {
                            found = true; // إذا تم العثور على الكلمة في أي خلية
                        }
                    });

                    // إذا تم العثور على الكلمة في الصف، نظهره
                    if (found) {
                        this.nodes().to$().show();
                    }
                });
                //$("select[name='Table_length']").prepend("<option value='10000' id='A10000'>10000</option>");
                $("select[name='Table_length'] option[value='10000']").prop("selected", true);
            }

            // يمكن إضافة وظيفة البحث تلقائيًا عند كتابة النص
            $('#search2').on('keyup', function () {
                searchRows();
            });
        });
</script>
}

Bnan.Ui/Areas/MAS/Views/RenterContract/_DataTableRenterContract.cshtml
@using Bnan.Ui.ViewModels.MAS

@using Bnan.Core.Extensions
@model RenterContractVM
@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> options
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    ViewData["returnUrl"] = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}


<table class=" tables-style table table-borderless " id="Table">
    <thead class="sticky-top">
        <tr>
            <th>@localizer["KilometersCut_s"]</th>
            <th>@localizer["RentalDay_s"]</th>
            <th>@localizer["ContractCount_s"]</th>
            <th >@localizer["LastVisit_s"]</th>
            <th >@localizer["FirstVisit_s"]</th>
            <th class="DifferAlign" style="max-width:240px;">@localizer["the_Renter"]</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            int no = 1;
        }
        @foreach (var item in Model.allCasRenterIds)
        {
            <tr onclick="location.href='@Url.Action("Edit", "RenterContract", new { id = item.CrCasRenterLessorId })'">


                <td><p>@(Model.allCasRenterLessor?.Where(x => x.CrCasRenterLessorId == item.CrCasRenterLessorId)?.Sum(x => x.CrCasRenterLessorContractKm)?.ToString("N2") ?? "0")</p></td>
                <td><p>@(Model.allCasRenterLessor?.Where(x => x.CrCasRenterLessorId == item.CrCasRenterLessorId)?.Sum(x => x.CrCasRenterLessorContractDays)?.ToString("0") ?? "0")</p></td>
                <td><p>@(Model.allCasRenterLessor?.Where(x => x.CrCasRenterLessorId == item.CrCasRenterLessorId)?.Sum(x => x.CrCasRenterLessorContractCount)?.ToString("0") ?? "0")</p></td>
                @if (requestCulture?.RequestCulture.UICulture.Name == "en-US")
                {
                    <td><p>@(Model.allCasRenterLessor?.Where(x => x.CrCasRenterLessorId == item.CrCasRenterLessorId)?.Max(x => x.CrCasRenterLessorDateLastContractual)?.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture) ?? " ")</p></td>
                    <td><p>@(Model.allCasRenterLessor?.Where(x => x.CrCasRenterLessorId == item.CrCasRenterLessorId)?.Min(x => x.CrCasRenterLessorDateFirstInteraction)?.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture) ?? " ")</p></td>
                }
                else
                {
                    <td><p>@(Model.allCasRenterLessor?.Where(x => x.CrCasRenterLessorId == item.CrCasRenterLessorId)?.Max(x => x.CrCasRenterLessorDateLastContractual)?.ToString("yyyy/MM/dd", CultureInfo.InvariantCulture) ?? " ")</p></td>
                    <td><p>@(Model.allCasRenterLessor?.Where(x => x.CrCasRenterLessorId == item.CrCasRenterLessorId)?.Min(x => x.CrCasRenterLessorDateFirstInteraction)?.ToString("yyyy/MM/dd", CultureInfo.InvariantCulture) ?? " ")</p></td>
                }

                @if (requestCulture?.RequestCulture.UICulture.Name == "en-US")
                {
                    <td class="DifferAlign">
                        <p class="FirstLineP">@(Model.all_Renters?.Find(x => x.CrMasRenterInformationId == item.CrCasRenterLessorId)?.CrMasRenterInformationEnName ??" ")</p>
                        <p class="secondLineP"> @item.CrCasRenterLessorId </p>
                    </td>
                }
                else
                {
                    <td class="DifferAlign">
                        <p class="FirstLineP">@(Model.all_Renters?.Find(x => x.CrMasRenterInformationId == item.CrCasRenterLessorId)?.CrMasRenterInformationArName ?? " ")</p>
                        <p class="secondLineP"> @item.CrCasRenterLessorId </p>
                    </td>
                }

                <td><p>@no</p></td>
                
                @*<td>
                    <div class="filter-number-td">
                        @{
                            var filterColor = "";
                            if (item.CrMasRenterInformationStatus == Status.Active) filterColor = "filter2-div";
                            else if (item.CrMasRenterInformationStatus == Status.Hold) filterColor = "filter1-div";
                            else if (item.CrMasRenterInformationStatus == Status.Deleted) filterColor = "filter3-div";
                        }
                        <div class="filters @filterColor"></div>
                        <div>@no</div>
                    </div>
                </td>*@
            </tr>
            no++;
        }

    </tbody>

</table>