Bnan.Ui/Areas/CAS/Controllers/CasReports/ReportFTPRenterController.cs
using AutoMapper;
using Bnan.Core.Extensions;
using Bnan.Core.Interfaces;
using Bnan.Core.Interfaces.Base;
using Bnan.Core.Interfaces.MAS;
using Bnan.Core.Models;
using Bnan.Inferastructure.Filters;
//using Bnan.Inferastructure.Repository.CAS;
using Bnan.Ui.Areas.Base.Controllers;
using Bnan.Ui.Areas.CAS.Controllers;
using Bnan.Ui.ViewModels.BS;
using Bnan.Ui.ViewModels.CAS;
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Azure;
using Microsoft.Extensions.Localization;
using Microsoft.IdentityModel.Tokens;
using NToastNotify;
using System.Globalization;
using System.Numerics;
namespace Bnan.Ui.Areas.CAS.Controllers.CasReports
{
    [Area("CAS")]
    [Authorize(Roles = "CAS")]
    [ServiceFilter(typeof(SetCurrentPathCASFilter))]
    public class ReportFTPRenterController : BaseController
    {
        private readonly IUserLoginsService _userLoginsService;
        private readonly IUserService _userService;
        private readonly IMasRenterInformation _masRenterInformation;
        private readonly IBaseRepo _baseRepo;
        private readonly IMasBase _masBase;
        private readonly IToastNotification _toastNotification;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IStringLocalizer<ReportFTPRenterController> _localizer;
        private readonly string pageNumber = SubTasks.FT_Renters_Report_Cas;


        public ReportFTPRenterController(UserManager<CrMasUserInformation> userManager, IUnitOfWork unitOfWork,
            IMapper mapper, IUserService userService, IMasRenterInformation masRenterInformation, IBaseRepo BaseRepo, IMasBase masBase,
            IUserLoginsService userLoginsService, IToastNotification toastNotification, IWebHostEnvironment webHostEnvironment, IStringLocalizer<ReportFTPRenterController> localizer) : base(userManager, unitOfWork, mapper)
        {
            _userService = userService;
            _masRenterInformation = masRenterInformation;
            _userLoginsService = userLoginsService;
            _baseRepo = BaseRepo;
            _masBase = masBase;
            _toastNotification = toastNotification;
            _webHostEnvironment = webHostEnvironment;
            _localizer = localizer;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {


            // Set page titles
            var user = await _userManager.GetUserAsync(User);
            await SetPageTitleAsync(string.Empty, pageNumber);
            // Check Validition
            if (!await _baseRepo.CheckValidation(user.CrMasUserInformationCode, pageNumber, Status.ViewInformation))
            {
                _toastNotification.AddErrorToastMessage(_localizer["AuthEmplpoyee_No_auth"], new ToastrOptions { PositionClass = _localizer["toastPostion"], Title = "", }); //  إلغاء العنوان الجزء العلوي
                return RedirectToAction("Index", "Home");
            }

            var all_CasRenterLessor = await _unitOfWork.CrCasRenterLessor.FindAllWithSelectAsNoTrackingAsync(
                predicate: x => x.CrCasRenterLessorCode == user.CrMasUserInformationLessor
                && x.CrCasRenterLessorContractCount > 0 && x.CrCasRenterLessorStatus != Status.Deleted,
                //x.CrCasCarInformationLastContractDate > start && x.CrCasCarInformationLastContractDate <= end,
                selectProjection: query => query.Select(x => new info_FTP_CasRenterLessor_Renter_VM
                {
                    CrCasRenterLessorId = x.CrCasRenterLessorId,
                    TradedAmount = x.CrCasRenterLessorContractTradedAmount,
                    CrCasRenterLessorCode = x.CrCasRenterLessorCode,
                    Renter_Ar = x.CrCasRenterLessorNavigation.CrMasRenterInformationArName,
                    Renter_En = x.CrCasRenterLessorNavigation.CrMasRenterInformationEnName,
                    TotalBalance = x.CrCasRenterLessorBalance,
                    AvailableBalance = x.CrCasRenterLessorAvailableBalance,
                    ReservedBalance = x.CrCasRenterLessorReservedBalance,
                })
                , includes: new string[] { "CrCasRenterLessorNavigation" }
                );

            all_CasRenterLessor = all_CasRenterLessor.DistinctBy(x => x.CrCasRenterLessorId).ToList();

            //var all_bonds = await _unitOfWork.CrCasAccountReceipt.FindCountByColumnAsync<CrCasAccountReceipt>(
            //       predicate: x => x.CrCasAccountReceiptLessorCode == user.CrMasUserInformationLessor && x.CrCasAccountReceiptType == "301",
            //       columnSelector: x => x.CrCasAccountReceiptRenterId  // تحديد العمود الذي نريد التجميع بناءً عليه
            //                                                       //,includes: new string[] { "RelatedEntity1", "RelatedEntity2" } 
            //       );
            //var all_exchanges = await _unitOfWork.CrCasAccountReceipt.FindCountByColumnAsync<CrCasAccountReceipt>(
            //   predicate: x => x.CrCasAccountReceiptLessorCode == user.CrMasUserInformationLessor && x.CrCasAccountReceiptType == "302",
            //   columnSelector: x => x.CrCasAccountReceiptRenterId  // تحديد العمود الذي نريد التجميع بناءً عليه
            //                                                       //,includes: new string[] { "RelatedEntity1", "RelatedEntity2" } 
            //   );


            if (all_CasRenterLessor?.Count == 0)
            {
                _toastNotification.AddErrorToastMessage(_localizer["NoDataToShow"], new ToastrOptions { PositionClass = _localizer["toastPostion"], Title = "", }); //  إلغاء العنوان الجزء العلوي
                return RedirectToAction("Index", "Home");
            }
            ViewBag.radio = "A";


            listReportFTPRenterVM VM = new listReportFTPRenterVM();
            VM.all_CasRenterLessor = all_CasRenterLessor;
            //VM.all_bonds = all_bonds;
            //VM.all_exchanges = all_exchanges;
            return View(VM);
        }

        [HttpGet]
        //[Route("/CAS/ReportFTPRenter/GetContractsByStatus")]
        public async Task<PartialViewResult> GetContractsByStatus(string status,string id,string start, string end)
        {
            var user = await _userManager.GetUserAsync(User);

            listReportFTPRenterVM VM = new listReportFTPRenterVM();

            if (start == "undefined-undefined-") start = "";
            if (end == "undefined-undefined-") end = "";
            if (string.IsNullOrEmpty(start) && string.IsNullOrEmpty(end))
            {
                start = DateTime.Now.AddMonths(-1).ToString("dd-MM-yyyy");
                end = DateTime.Now.ToString("dd-MM-yyyy");
            }
            if (!string.IsNullOrEmpty(status) && !string.IsNullOrEmpty(id) && !string.IsNullOrEmpty(start) && !string.IsNullOrEmpty(end))
            {
                var start_Date = DateTime.Parse(start);
                var end_Date = DateTime.Parse(end).AddDays(1);
                VM.start_Date = start_Date.ToString("yyyy-MM-dd");
                VM.end_Date = end_Date.AddDays(-1).ToString("yyyy-MM-dd");

                await SetPageTitleAsync(Status.Update, pageNumber);
                var all_Recipts = await _unitOfWork.CrCasAccountReceipt.FindAllWithSelectAsNoTrackingAsync(
                //predicate: x => x.CrCasCarInformationStatus != Status.Deleted,
                predicate: x => x.CrCasAccountReceiptRenterId == id
                && x.CrCasAccountReceiptLessorCode == user.CrMasUserInformationLessor
                && (x.CrCasAccountReceiptDate > start_Date && x.CrCasAccountReceiptDate <= end_Date)
                ,
                selectProjection: query => query.Select(x => new ReciptVM_Renter
                {
                    CrCasAccountReceiptNo = x.CrCasAccountReceiptNo,
                    CrCasAccountReceiptType = x.CrCasAccountReceiptType,
                    CrCasAccountReceiptDate = x.CrCasAccountReceiptDate,
                    CrCasAccountReceiptLessorCode = x.CrCasAccountReceiptLessorCode,
                    CrCasAccountReceiptReferenceType = x.CrCasAccountReceiptReferenceType,
                    CrCasAccountReceiptSalesPoint = x.CrCasAccountReceiptSalesPoint,
                    CrCasAccountReceiptReferenceNo = x.CrCasAccountReceiptReferenceNo,
                    CrCasAccountReceiptPayment = x.CrCasAccountReceiptPayment,
                    CrCasAccountReceiptReceipt = x.CrCasAccountReceiptReceipt,
                    CrCasAccountReceiptRenterId = x.CrCasAccountReceiptRenterId,
                    CrCasAccountReceiptUser = x.CrCasAccountReceiptUser,
                    CrCasAccountReceiptIsPassing = x.CrCasAccountReceiptIsPassing,
                    CrCasAccountReceiptPassingReference = x.CrCasAccountReceiptPassingReference,
                    CrCasAccountReceiptPassingUser = x.CrCasAccountReceiptPassingUser,
                    CrCasAccountReceiptPdfFile = x.CrCasAccountReceiptPdfFile,
                    PaymentMethod_Ar = x.CrCasAccountReceiptPaymentMethodNavigation.CrMasSupAccountPaymentMethodArName,
                    PaymentMethod_En = x.CrCasAccountReceiptPaymentMethodNavigation.CrMasSupAccountPaymentMethodEnName,
                    ReferanceType_Ar = x.CrCasAccountReceiptReferenceTypeNavigation.CrMasSupAccountReceiptReferenceArName,
                    ReferanceType_En = x.CrCasAccountReceiptReferenceTypeNavigation.CrMasSupAccountReceiptReferenceEnName,
                    Salespoint_Ar = x.CrCasAccountReceiptSalesPointNavigation.CrCasAccountSalesPointArName,
                    Salespoint_En = x.CrCasAccountReceiptSalesPointNavigation.CrCasAccountSalesPointEnName,
                    branch_Ar = x.CrCasAccountReceiptNavigation.CrCasBranchInformationArShortName,
                    branch_En = x.CrCasAccountReceiptNavigation.CrCasBranchInformationEnShortName,

Bnan.Ui/Areas/CAS/Views/ReportFTPRenter/Index.cshtml
@using Bnan.Core.Extensions
@using Bnan.Ui.ViewModels.CAS;
@* @model IEnumerable<CrMasRenterInformation>
*@
@model listReportFTPRenterVM
@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> options
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
       ViewData["returnUrl"] = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}"; 
    ViewData["Page-title"] = @localizer["RenterInformations Data"];
    ViewData["Page-Hint"] = @localizer["RenterInformations Hint"];
}

@*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">*@


<div class="col d-flex align-items-center justify-content-center" style=" z-index:2;">
    <div class="container main-container">
        <form action="">
                <div class="row g-3 mb-5">
                <div class="col">
                        <h3> @localizer["FinancialTransactionOfRenter Data"]  </h3>
                </div>
                    <div class="col-12 col-lg-6 d-flex justify-content-end">

                        <div class="col-12 col-md-8 search-input-col">
                            <div class="form-outline w-100" data-mdb-input-init>
                                <span class="fa fa-search"></span>
                                <input type="search" id="search2" class="form-control inputs search-input" aria-label="Search" autofocus autocomplete="off" />
                            </div>
                        </div>

                    </div>
            </div>

            <div class="row table-row px-3">
                <div class="col  scroll-table-div filter-search-reportTable table-responsive-sm w-100 dataTable">
                    <partial name="_DataTableReportFTPRenter" />
                </div>
            </div>
        </form>
            <a asp-area="CAS" asp-controller="Home" asp-action="Index" data-bs-toggle="tooltip" data-bs-placement="top"
           data-bs-custom-class="custom-tooltip" data-bs-title="@localizer["BackToHome"]" class="new-Page-icon">
            <img src="~/MasSystem/images/back to main.svg" alt="man">
        </a>
    </div>
    </div>
@*////////////////////////////*@@*////////////////////////////*@@*////////////////////////////*@
@*////////////////////////////*@@*////////////////////////////*@@*////////////////////////////*@

    @section Scripts{
    <!-- تحميل مكتبة jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- تحميل مكتبة DataTables -->
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

@*    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
    // تهيئة flatpickr مع التنسيق المطلوب
    flatpickr("#start_date", {
        dateFormat: "d/m/Y", // تنسيق التاريخ إلى يوم/شهر/سنة
    });
        // تهيئة flatpickr مع التنسيق المطلوب
    flatpickr("#end_date", {
        dateFormat: "d/m/Y", // تنسيق التاريخ إلى يوم/شهر/سنة
    });
</script>*@

<script>
        $(document).ready(function () {
            //$("#start_date").val('@Model.start_Date'); //  اضافة قيمة البداية من ال viewModel
            //$("#end_date").val('@Model.end_Date'); //  اضافة قيمة النهاية من ال viewModel

            // لجعل الحالة حسب ما هي جاية من index نشط او الكل
            //$("input[name='customRadio'][value='" + '@ViewBag.radio' + "']").prop("checked", true);
            $("#min-loader").toggleClass("d-none", true); // اخفاء loader بعد انتهاء تحميل الصفحة
                        
            //var today = new Date();
            //$("#start_date").datepicker({
            //    dateFormat: 'yy/mm/dd',  // التاريخ إلى يوم/شهر/سنة
            //    maxDate: today,
            //});
            //$("#end_date").datepicker({
            //    dateFormat: 'yy/mm/dd',  // التاريخ إلى يوم/شهر/سنة
            //    maxDate: today,
            //});

 
            ///////
            // تهيئة DataTable
            var table2 = $('#Table').DataTable({
                ordering: false, // تعطيل الترتيب التلقائي للصفوف
                stateSave: true,   // حفظ حالة الجدول
            });
            end_init_ShowDatatable();
        });

        function end_init_ShowDatatable(){
            $("#min-loader").toggleClass("d-none", true);
            $("select[name='Table_length']").prepend("<option value='10000' id='A10000'>10000</option>");
            //$("select[name='Table_length'] option[value='10000']").prop("selected", true);
            $("select[name='Table_length']").val('10000').change();
            $("#Table_info").css("display", "none");
            $("#Table_previous").css("display", "none");
            $("#Table_next").css("display", "none");
            $("#Table_length").css("display", "none");
            $("#Table_filter").css("display", "none");
            $(".paginate_button").css("display", "none");
            $(".ellipsis").css("display", "none");
            $("select[name='Table_length'] option[value='10000']").prop("selected", true);
        }

        // دالة للبحث عن كلمة في جميع الصفوف
        function searchRows() {
            var table = $('#Table').DataTable();
            end_init_ShowDatatable();
            var keyword = $('#search2').val().toLowerCase(); // الكلمة المدخلة للبحث (تحويلها إلى حروف صغيرة)

            // إخفاء كل الصفوف أولاً
            table.rows().every(function () {
                this.nodes().to$().hide(); // إخفاء الصف
            });

            // التكرار عبر كل الصفوف
            table.rows().every(function () {
                var row = this.data();
                var found = false;

                // التكرار عبر كل الخلايا في الصف
                row.forEach(function (cell) {
                    if (cell.toString().toLowerCase().includes(keyword)) {
                        found = true; // إذا تم العثور على الكلمة في أي خلية
                    }
                });

                // إذا تم العثور على الكلمة في الصف، نظهره
                if (found) {
                    this.nodes().to$().show();
                }
            });
            //$("select[name='Table_length']").prepend("<option value='10000' id='A10000'>10000</option>");
        }

        // يمكن إضافة وظيفة البحث تلقائيًا عند كتابة النص
        $('#search2').on('keyup', function () {
            $("#min-loader").removeClass("d-none");
            searchRows();
            $("#min-loader").toggleClass("d-none", true);
        });

</script>
    <script>
        //get ReportFTPRenter By Status function
        function GetContractsByStatusFitler(status, start, end) {
            $.ajax({
                type: "GET",
                data: {
                    status: status, start: start, end: end
                },
                url: "@Url.Action("GetContractsByStatus", "ReportFTPRenter", new { Area = "CAS" })",
                success: function (response) {
                    $("#min-loader").toggleClass("d-none", true);
                    $(".dataTable").html(response);
                },
            })
        }

        $("input[name='customRadio']").on("click", function () {
            const status = $(this).val();
            const start = $("#start_date").val(); // الحصول على قيمة البداية
            const end = $("#end_date").val(); // الحصول على قيمة النهاية

            //const start1 = $("#start_date").val(); // الحصول على قيمة البداية
            //var dateParts = start1.split("/"); // تقسيم التاريخ إلى أجزاء
            //var formattedDate1 = dateParts[2] + "-" + dateParts[1] + "-" + dateParts[0]; // تحويله إلى yyyy-MM-dd
            //var start = formattedDate1;// الحصول على قيمة النهاية
            //const end2 = $("#end_date").val(); // الحصول على قيمة البداية
            //var dateParts = end2.split("/"); // تقسيم التاريخ إلى أجزاء
            //var formattedDate2 = dateParts[2] + "-" + dateParts[1] + "-" + dateParts[0]; // تحويله إلى yyyy-MM-dd
            //var end = formattedDate2;// الحصول على قيمة النهاية
            
            $("#min-loader").removeClass("d-none");
            $("#search2").val("");
            GetContractsByStatusFitler(status, start, end);
        });

        // عند كتابة أي شيء في حقل البحث، تحديث الفلتر
        $("#btn_view").on("click", function () {
            const status = $("input[name='customRadio']:checked").val(); // الحصول على القيمة المحددة من الراديو
            const start = $("#start_date").val(); // الحصول على قيمة البداية
            const end = $("#end_date").val(); // الحصول على قيمة النهاية

            //const start1 = $("#start_date").val(); // الحصول على قيمة البداية
            //var dateParts = start1.split("/"); // تقسيم التاريخ إلى أجزاء
            //var formattedDate1 = dateParts[2] + "-" + dateParts[1] + "-" + dateParts[0]; // تحويله إلى yyyy-MM-dd
            //var start = formattedDate1;// الحصول على قيمة النهاية
            //const end2 = $("#end_date").val(); // الحصول على قيمة البداية
            //var dateParts = end2.split("/"); // تقسيم التاريخ إلى أجزاء
            //var formattedDate2 = dateParts[2] + "-" + dateParts[1] + "-" + dateParts[0]; // تحويله إلى yyyy-MM-dd
            //var end = formattedDate2;// الحصول على قيمة النهاية
            
            $("#min-loader").removeClass("d-none");
            $("#search2").val("");
            GetContractsByStatusFitler(status, start, end);
        });
    </script>
}

Bnan.Ui/Areas/CAS/Views/ReportFTPRenter/_DataTableReportFTPRenter.cshtml
@using Bnan.Core.Extensions
@using Bnan.Ui.ViewModels.CAS;
@model listReportFTPRenterVM
@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> options
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    ViewData["returnUrl"] = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}


<table class=" tables-style table table-borderless " id="Table">
    <thead class="sticky-top">
        <tr>

            <th>@localizer["Amountstraded"]</th>
            <th>@localizer["FTR_Reserved_Balance"]</th>
            <th>@localizer["FTR_Avilable_Balance"]</th>
            <th>@localizer["FTR_Balance"]</th>
            <th class="DifferAlign" style="max-width:220px;"> @localizer["Renter_Name"]</th>
            <th></th>

        </tr>
    </thead>
    <tbody>
        @{
            var no = 1;
        }
        @foreach (var item in Model.all_CasRenterLessor)
        {
            var Renter = " ";
            if (requestCulture?.RequestCulture.UICulture.Name == "en-US")
            {
                Renter = item.Renter_En;

            }
            else
            {
                Renter = item.Renter_Ar;

            }
            //var LastDate = item.CrCasCarInformationLastContractDate;

            <tr onclick="location.href='@Url.Action("Edit", "ReportFTPRenter", new { id = item.CrCasRenterLessorId})'">
                <td>
                    @((item.TradedAmount ?? 0.0m).ToString("N2"))
                </td>
                <td>
                    @((item.ReservedBalance??0.0m).ToString("N2"))
                </td>
                <td>
                    @((item.AvailableBalance ?? 0.0m).ToString("N2"))
                </td>
                <td>
                    @((item.TotalBalance ?? 0.0m).ToString("N2"))
                </td>


                <td class="DifferAlign">
                    <p class="FirstLineP">@Renter </p>
                    <p class="secondLineP">@item.CrCasRenterLessorId</p>
                </td>
                <td>
                    @no
                </td>
                                    
            </tr>
            no++;
        }

    </tbody>

</table>

Bnan.Ui/Areas/CAS/Views/ReportFTPRenter/_EditpartDataTableReportFTPRenter.cshtml
@using Bnan.Core.Extensions
@using Bnan.Ui.ViewModels.CAS;
@model listReportFTPRenterVM
@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> options
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    ViewData["returnUrl"] = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div hidden>
    <input value="@Model.summition?.Creditor_Total?.ToString("N2",CultureInfo.InvariantCulture)" id="in_credit" name="in_credit" hidden />
    <input value="@Model.summition?.Debitor_Total?.ToString("N2",CultureInfo.InvariantCulture)" id="in_debit" name="in_debit" hidden />
</div>

                        

<div class="col-md-12">
    <div class="row table-row px-3">
        <div class="col  scroll-extended-table-div scroll-table-div  table-responsive-sm  w-100  ">
            <table class=" tables-style table table-borderless " id="Table">
                <thead class="sticky-top">
                    <tr>

                        <th>@localizer["FTR_bond_pdf_n"]</th>
                        <th class="DifferAlign"> @localizer["FTR_User_Transector"]</th>
                        <th>@localizer["FTR_previuos_Balance"]</th>
                        <th>@localizer["FTR_Debtor"]</th>
                        <th> @localizer["FTR_Creditor"]</th>
                        <th class="DifferAlign"> @localizer["FTR_PaymentMethod"]</th>
                        <th class="DifferAlign" style="min-width:200px;max-width:240px"> @localizer["FTR_Reference_Type"]</th>
                        <th class="DifferAlign"> @localizer["Branch"]</th>
                        <th class="DifferAlign" style="min-width:200px;max-width:240px">@localizer["FTR_Serial_No_n"]</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var no = 1;
                    }
                    @foreach (var item in Model.all_Recipts)
                    {

                        var credit = item.CrCasAccountReceiptPayment;
                        var debit = item.CrCasAccountReceiptReceipt;
                        var userPreviousBalance = item.userPreviousBalance;
                        var issuedDate = item.CrCasAccountReceiptDate;
                        var paymentMethod = " ";
                        var RefrenceType = " ";
                        var Employee = " ";
                        var branch = " ";
                        var salesPoint = " ";

                        var bond_pdf = "#";
                        var bond_pdf_blank = "";
                        if (item.CrCasAccountReceiptPdfFile != null && item.CrCasAccountReceiptPdfFile != "") { bond_pdf = item.CrCasAccountReceiptPdfFile?.ToString().Replace("~", ""); bond_pdf_blank = "_blank"; }

                        if (requestCulture?.RequestCulture.UICulture.Name == "en-US")
                        {
                            paymentMethod = item.PaymentMethod_En;
                            RefrenceType = item.ReferanceType_En;
                            Employee = Model.all_UserData?.Find(x => x.CrMasUserInformationCode== item.CrCasAccountReceiptUser)?.CrMasUserInformationEnName;
                            branch = item.branch_En ?? " ";
                            salesPoint = item.Salespoint_En ?? " ";
                        }
                        else
                        {
                            paymentMethod = item.PaymentMethod_Ar;
                            RefrenceType = item.ReferanceType_Ar;
                            Employee = Model.all_UserData?.Find(x => x.CrMasUserInformationCode == item.CrCasAccountReceiptUser)?.CrMasUserInformationArName;
                            branch = item.branch_Ar ?? " ";
                            salesPoint = item.Salespoint_Ar ?? " ";
                        }


                        <tr onclick="getDetails('@item.CrCasAccountReceiptNo')" style="cursor:pointer;">
                            <td><a href="@bond_pdf" target="@bond_pdf_blank" onclick="PdfClicked()"><img src="~/MasSystem/images/Rectangle 197.svg"></a></td>
                            <td>
                                <p class="DifferAlign">@Employee</p>
                            </td>
                            <td>
                                <p>@userPreviousBalance?.ToString("N2",CultureInfo.InvariantCulture)</p>
                            </td>
                            <td>
                                <p>@debit?.ToString("N2",CultureInfo.InvariantCulture)</p>
                            </td>
                            <td>
                                <p>@credit?.ToString("N2",CultureInfo.InvariantCulture)</p>
                            </td>
                            <td class="DifferAlign">
                                <p class="FirstLineP">@salesPoint</p>
                                <p class="secondLineP">@paymentMethod</p>
                            </td>
                            <td class="DifferAlign">
                                <p class="FirstLineP">@item.CrCasAccountReceiptReferenceNo</p>
                                <p class="secondLineP">@RefrenceType</p>
                            </td>
                            <td>
                                <p class="DifferAlign">@branch</p>
                            </td>



                            <td class="DifferAlign">
                                <p class="FirstLineP"> @item.CrCasAccountReceiptNo</p>
                                <div class="d-flex justify-content-end gap-1 gap-md-5 flex-wrap">
                                    <div class="d-flex justify-content-end gap-1">
                                        @if (requestCulture?.RequestCulture.UICulture.Name == "en-US"){
                                            <p class="secondLineP">
                                                <span class="time">@issuedDate?.ToString("HH:mm -",CultureInfo.InvariantCulture)</span>@issuedDate?.ToString("dd/MM/yyyy",CultureInfo.InvariantCulture)
                                            </p>
                                        }
                                        else
                                        {
                                            <p class="secondLineP">
                                                @issuedDate?.ToString("dd/MM/yyyy",CultureInfo.InvariantCulture)<span class="time">@issuedDate?.ToString("- HH:mm",CultureInfo.InvariantCulture)</span>
                                            </p>
                                        }
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="filter-number-td">
                                    @if (item.CrCasAccountReceiptIsPassing == "1")
                                    {
                                        <div class="filters filter2-div"></div>
                                    }
                                    else if (item.CrCasAccountReceiptIsPassing == "2")
                                    {
                                        <div class="filters filter1-div"></div>
                                    }
                                    else if (item.CrCasAccountReceiptIsPassing == "3")
                                    {
                                        <div class="filters filter3-div"></div>
                                    }
                                    else if (item.CrCasAccountReceiptIsPassing == "4")
                                    {
                                        <div class="filters filter3-div"></div>
                                    }


                                    <div>@no</div>

                                </div>
                            </td>
                            
                            
                        </tr>
                        no++;
                    }

                </tbody>
            </table>

        </div>
    </div>

</div>