Bnan.Ui/Areas/BS/Controllers/ContractSettlementController.cs
using AutoMapper;
using Bnan.Core.Extensions;
using Bnan.Core.Interfaces;
using Bnan.Core.Models;
using Bnan.Inferastructure.Extensions;
using Bnan.Ui.Areas.Base.Controllers;
using Bnan.Ui.ViewModels.BS;
using Bnan.Ui.ViewModels.BS.CreateContract;
using Bnan.Ui.ViewModels.CAS;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using NToastNotify;
using System.Globalization;

namespace Bnan.Ui.Areas.BS.Controllers
{
    [Area("BS")]
    [Authorize(Roles = "BS")]

    public class ContractSettlementController : BaseController
    {
        private readonly IToastNotification _toastNotification;
        private readonly IStringLocalizer<ContractSettlementController> _localizer;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IContractSettlement _contractSettlement;
        private readonly IConvertedText _convertedText;
        public ContractSettlementController(IStringLocalizer<ContractSettlementController> localizer, IUnitOfWork unitOfWork, UserManager<CrMasUserInformation> userManager, IMapper mapper, IToastNotification toastNotification, IContract contractServices, IWebHostEnvironment hostingEnvironment, IContractSettlement contractSettlement, IConvertedText convertedText) : base(userManager, unitOfWork, mapper)
        {
            _localizer = localizer;
            _toastNotification = toastNotification;
            _hostingEnvironment = hostingEnvironment;
            _contractSettlement = contractSettlement;
            _convertedText = convertedText;
        }

        public async Task<IActionResult> Index()
        {
            //To Set Title 
            var titles = await setTitle("503", "5503001", "5");
            await ViewData.SetPageTitleAsync(titles[0], "", titles[2], "", "", titles[3]);

            var userLogin = await _userManager.GetUserAsync(User);
            var lessorCode = userLogin.CrMasUserInformationLessor;
            var bsLayoutVM = await GetBranchesAndLayout();
            var contracts = _unitOfWork.CrCasRenterContractBasic.FindAll(x => (x.CrCasRenterContractBasicStatus == Status.Active || x.CrCasRenterContractBasicStatus == Status.Expire) &&
                                                                               x.CrCasRenterContractBasicLessor == lessorCode && x.CrCasRenterContractBasicBranch == bsLayoutVM.SelectedBranch,
                                                                               new[] { "CrCasRenterContractBasicCarSerailNoNavigation", "CrCasRenterContractBasic5.CrCasRenterLessorNavigation", "CrCasRenterContractBasic1" }).ToList();
            var contractReceivingTheCarFromAnotherBranch = _unitOfWork.CrCasRenterContractAdditional.FindAll(x => x.CrCasRenterContractAdditionalCode == "5000000003" || x.CrCasRenterContractAdditionalCode == "5000000004").ToList();
            foreach (var item in contractReceivingTheCarFromAnotherBranch)
            {
                var contract2 = _unitOfWork.CrCasRenterContractBasic.Find(x => x.CrCasRenterContractBasicNo == item.CrCasRenterContractAdditionalNo && (x.CrCasRenterContractBasicStatus == Status.Active || x.CrCasRenterContractBasicStatus == Status.Expire) &&
                                                                               x.CrCasRenterContractBasicLessor == lessorCode,
                                                                               new[] { "CrCasRenterContractBasicCarSerailNoNavigation", "CrCasRenterContractBasic5.CrCasRenterLessorNavigation", "CrCasRenterContractBasic1" });
                if (contract2 != null && !contracts.Contains(contract2)) contracts.Add(contract2);
            }
            var contractMap = _mapper.Map<List<ContractSettlementVM>>(contracts);
            foreach (var contract in contractMap)
            {
                var authContract = _unitOfWork.CrCasRenterContractAuthorization.Find(x => x.CrCasRenterContractAuthorizationLessor == lessorCode &&
                x.CrCasRenterContractAuthorizationContractNo == contract.CrCasRenterContractBasicNo);
                var Invoice = _unitOfWork.CrCasAccountInvoice.FindAll(x => x.CrCasAccountInvoiceReferenceContract == contract.CrCasRenterContractBasicNo).LastOrDefault()?.CrCasAccountInvoicePdfFile;
                contract.InvoicePdfPath = Invoice;
                if (authContract != null) contract.AuthEndDate = authContract.CrCasRenterContractAuthorizationEndDate;

            }



            bsLayoutVM.ContractSettlements = contractMap.Where(x => x.AuthEndDate > DateTime.Now).OrderBy(x => x.CrCasRenterContractBasicExpectedEndDate).ToList();
            return View(bsLayoutVM);
        }
        [HttpGet]
        public async Task<PartialViewResult> GetContractBySearch(string search)
        {
            var userLogin = await _userManager.GetUserAsync(User);
            var lessorCode = userLogin.CrMasUserInformationLessor;
            var bsLayoutVM = await GetBranchesAndLayout();
            var contracts = _unitOfWork.CrCasRenterContractBasic.FindAll(x => (x.CrCasRenterContractBasicStatus == Status.Active || x.CrCasRenterContractBasicStatus == Status.Expire) &&
                                                                               x.CrCasRenterContractBasicLessor == lessorCode && x.CrCasRenterContractBasicBranch == bsLayoutVM.SelectedBranch,
                                                                               new[] { "CrCasRenterContractBasicCarSerailNoNavigation", "CrCasRenterContractBasic5.CrCasRenterLessorNavigation", "CrCasRenterContractBasic1" }).ToList();
            var contractReceivingTheCarFromAnotherBranch = _unitOfWork.CrCasRenterContractAdditional.FindAll(x => x.CrCasRenterContractAdditionalCode == "5000000003").ToList();
            foreach (var item in contractReceivingTheCarFromAnotherBranch)
            {
                var contract2 = _unitOfWork.CrCasRenterContractBasic.Find(x => x.CrCasRenterContractBasicNo == item.CrCasRenterContractAdditionalNo && (x.CrCasRenterContractBasicStatus == Status.Active || x.CrCasRenterContractBasicStatus == Status.Expire) &&
                                                                               x.CrCasRenterContractBasicLessor == lessorCode,
                                                                               new[] { "CrCasRenterContractBasicCarSerailNoNavigation", "CrCasRenterContractBasic5.CrCasRenterLessorNavigation", "CrCasRenterContractBasic1" });
                if (contract2 != null && !contracts.Contains(contract2)) contracts.Add(contract2);
            }
            var contractMap = _mapper.Map<List<ContractSettlementVM>>(contracts);
            foreach (var contract in contractMap)
            {
                var authContract = _unitOfWork.CrCasRenterContractAuthorization.Find(x => x.CrCasRenterContractAuthorizationLessor == lessorCode &&
                x.CrCasRenterContractAuthorizationContractNo == contract.CrCasRenterContractBasicNo);
                var Invoice = _unitOfWork.CrCasAccountInvoice.FindAll(x => x.CrCasAccountInvoiceReferenceContract == contract.CrCasRenterContractBasicNo).LastOrDefault().CrCasAccountInvoicePdfFile;
                contract.InvoicePdfPath = Invoice;
                if (authContract != null) contract.AuthEndDate = authContract.CrCasRenterContractAuthorizationEndDate;
            }

            if (!string.IsNullOrEmpty(search))
            {

                bsLayoutVM.ContractSettlements = contractMap.Where(x => x.AuthEndDate > DateTime.Now &&
                                                                                               (x.CrCasRenterContractBasicNo.Contains(search) ||
                                                                                                x.CrCasRenterContractBasic5.CrCasRenterLessorNavigation.CrMasRenterInformationArName.Contains(search) ||
                                                                                                x.CrCasRenterContractBasicCarSerailNoNavigation.CrCasCarInformationConcatenateArName.Contains(search) ||
                                                                                                x.CrCasRenterContractBasic5.CrCasRenterLessorNavigation.CrMasRenterInformationEnName.ToLower().Contains(search) ||
                                                                                                x.CrCasRenterContractBasicCarSerailNoNavigation.CrCasCarInformationConcatenateEnName.ToLower().Contains(search))).OrderBy(x => x.CrCasRenterContractBasicExpectedEndDate).ToList();
                return PartialView("_ContractSettlement", bsLayoutVM);
            }
            bsLayoutVM.ContractSettlements = contractMap.Where(x => x.AuthEndDate > DateTime.Now).OrderBy(x => x.CrCasRenterContractBasicExpectedEndDate).ToList();
            return PartialView("_ContractSettlement", bsLayoutVM);
        }

        [HttpGet]
        public async Task<IActionResult> Create(string id)
        {
            //To Set Title 
            var titles = await setTitle("503", "5503001", "5");
            await ViewData.SetPageTitleAsync(titles[0], "", titles[2], "", "", titles[3]);
            var userLogin = await _userManager.GetUserAsync(User);
            var lessorCode = userLogin.CrMasUserInformationLessor;
            var bsLayoutVM = await GetBranchesAndLayout();
            var contractList = await _unitOfWork.CrCasRenterContractBasic.FindAllAsNoTrackingAsync(x => x.CrCasRenterContractBasicNo == id,
                                                                                     new[] { "CrCasRenterContractBasic5.CrCasRenterLessorNavigation",
                                                                                             "CrCasRenterContractBasicCarSerailNoNavigation.CrCasCarAdvantages",

Bnan.Ui/Areas/BS/Views/ContractSettlement/Index.cshtml
@using Bnan.Core.Extensions;
@using Bnan.Ui.ViewModels.BS;
@using Microsoft.AspNetCore.Identity;
@using Microsoft.EntityFrameworkCore;
@using Newtonsoft.Json;
@model BSLayoutVM
@inject IViewLocalizer localizer
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    ViewData["returnUrl"] = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}
<link href="~/BranchSys/Pages/css/style.css" rel="styleSheet">
@if (requestCulture?.RequestCulture.UICulture.Name != "ar-EG")
{
    <link href="~/BranchSys/Pages/css/English_style.css" rel="styleSheet">
}
<div class="container-fluid">
    <section class="section-mainCard">
        <div class="row justify-content-center w-100 h-100">
            <div class="col-11 col-sm-10 col-md-11 col-lg-11 col-xl-10 text-center p-0 ">
                <div class="card main-card ">
                    <div class="row pt-2">
                        <a asp-area="BS" asp-action="Index" asp-controller="Home" style="width: fit-content;">
                            <div>
                                <img src="~/BranchSys/Pages/img/Close.svg" alt="close_icon" class="close-icon" style="margin-left: 10px">
                            </div>
                        </a>
                    </div>
                    <div class="row layout-row">

                        <div class="row" style="flex-direction: row-reverse;">
                            <div class="col justify-content-center d-flex title-row">
                                <h1 class="card-title">
                                    @localizer["ListOfActiveContracts"]
                                </h1>
                            </div>

                        </div>
                        <div class="row justify-content-center h-100 content-row">

                            <div class="col-md-11 mx-0 h-100">

                                <form id="contract-extension-form">

                                    <fieldset>
                                        <div class="form-card card-tables">
                                            <div class="row pb-4 seacrh-row gap-4" style="flex-direction: row-reverse;justify-content: space-between;">
                                                <div class="col-12 d-flex align-items-center flex-row-reverse Search-col align-items-baseline" style="justify-content: flex-start;flex-wrap: wrap;">
                                                    <div class="col-auto">
                                                        <label for="search"> @localizer["search"]</label>
                                                    </div>
                                                    <div class="col-auto">
                                                        <div class="form-outline" data-mdb-input-init>
                                                            <span class="fa fa-search"></span>
                                                            <input type="search" id="search" class="form-control inputs @(requestCulture?.RequestCulture.UICulture.Name != "ar-EG" ? "text-start" : "text-end")" name="search" aria-label="Search" autofocus />
                                                        </div>
                                                    </div>
                                                </div>
                                               @*  <div class="col-12 d-flex  radio-container px-4"
                                                     style="flex-direction: row-reverse;flex-wrap: wrap;">
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input custom" type="radio"
                                                               name="Options" id="all" value="All" checked />
                                                        <label class="form-check-label"
                                                               for="all">الكل</label>
                                                    </div>

                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input custom" type="radio"
                                                               name="Options" id="endedd" value="endedd" />
                                                        <label class="form-check-label "
                                                               for="endedd" style="color:#aa0d02">منتهي</label>
                                                    </div>

                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input custom" type="radio"
                                                               name="Options" id="today" value="today" />
                                                        <label class="form-check-label "
                                                               for="today" style="color:#FF9626">اليوم</label>
                                                    </div>
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input custom" type="radio"
                                                               name="Options" id="tomorrow" value="tomorrow" />
                                                        <label class="form-check-label tomorrow"
                                                               for="tomorrow" style="color:#39629C">غدًا</label>
                                                    </div>
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input custom" type="radio"
                                                               name="Options" id="later" value="later" />
                                                        <label class="form-check-label later"
                                                               for="later" style="color:#70399C">لاحقًا</label>
                                                    </div>
                                                </div> *@
                                            </div>
                                            <div class="row table-row px-3">
                                                <div class="col  scroll-table-div  table-responsive-sm  w-100 dataTable ">
                                                        <partial name="_ContractSettlement" />
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>


<footer class="fixed-bottom-xl">
    <div class="before-footer-widget">
        <svg width: 100%; height:auto viewbox="0 0 2444 132">
            <path fill="rgba(254, 248, 232, 1)" fill-rule="evenodd"
                  d="M1222 0h1222c-444.13 88-852.127 132-1223.993 132C849.253 132 442.585 88.263 0 .789V0h1222z">
            </path>
        </svg>
    </div>

</footer>
@section scripts {

    <script>
        //get AccountBank By Status and Search function
        function GetContractFilter(search) {
            $.ajax({
                type: "GET",
                data: {
                    search: search
                },
                url: "@Url.Action("GetContractBySearch", "ContractSettlement", new { Area = "BS" })",
                success: function (response) {
                    $(".dataTable").html(response);
                },
            });
        }

        //on Change Search Input
        $("#search").on("input", function () {
            var searchValue = $(this).val();
            GetContractFilter(searchValue);
        });
    </script>
}

Bnan.Ui/Areas/BS/Views/ContractSettlement/_ContractSettlement.cshtml
@using Bnan.Ui.ViewModels.BS;
@model BSLayoutVM
@inject IViewLocalizer localizer
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    ViewData["returnUrl"] = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}


<table class=" tables-style table table-borderless " id="settelmentListTable">
    <thead>
        <tr>
@*             <th scope="col">@localizer["Contract"]</th>
 *@            <th scope="col" class="not-in-mobile @(requestCulture?.RequestCulture.UICulture.Name == "ar-EG" ? "text-right" : "text-left")">
                @localizer["Car"]
            </th>
            <th scope="col" class="not-in-mobile @(requestCulture?.RequestCulture.UICulture.Name == "ar-EG" ? "text-right" : "text-left")">
                @localizer["Renterr"]
            </th>
            <th scope="col">@localizer["Remaining"]</th>
            <th scope="col">@localizer["ContractNo"]</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            int no = 1;
        }
        @foreach (var item in Model.ContractSettlements)
        {
            <tr style="cursor:pointer">

                @* <td>
                    @if (requestCulture?.RequestCulture.UICulture.Name != "ar-EG")
                    {
                        <a href="@Url.Content(item.CrCasRenterContractBasicEnPdfFile.ToString())" target="_blank" class="pdf-link"><img src="/BranchSys/Pages/img/Rectangle 196.svg" alt="pdf file link"></a>
                    }
                    else
                    {
                        <a href="@Url.Content(item.CrCasRenterContractBasicPdfFile.ToString())" target="_blank" class="pdf-link"><img src="/BranchSys/Pages/img/Rectangle 196.svg" alt="pdf file link"></a>
                    }
                </td> *@

                @if (requestCulture?.RequestCulture.UICulture.Name != "ar-EG")
                {
                    <td class="car not-in-mobile text-left" onclick="location.href='@Url.Action("Create", "ContractSettlement", new { id = item.CrCasRenterContractBasicNo })'">
                        @item.CrCasRenterContractBasicCarSerailNoNavigation?.CrCasCarInformationConcatenateEnName
                    </td>
                }
                else
                {
                    <td class="car not-in-mobile text-right" onclick="location.href='@Url.Action("Create", "ContractSettlement", new { id = item.CrCasRenterContractBasicNo })'">
                        @item.CrCasRenterContractBasicCarSerailNoNavigation?.CrCasCarInformationConcatenateArName
                    </td>
                }

                @if (requestCulture?.RequestCulture.UICulture.Name != "ar-EG")
                {
                    <td class="name not-in-mobile text-left" onclick="location.href='@Url.Action("Create", "ContractSettlement", new { id = item.CrCasRenterContractBasicNo })'">
                        @item.CrCasRenterContractBasic5?.CrCasRenterLessorNavigation.CrMasRenterInformationEnName
                    </td>
                }
                else
                {
                    <td class="name not-in-mobile text-right" onclick="location.href='@Url.Action("Create", "ContractSettlement", new { id = item.CrCasRenterContractBasicNo })'">
                        @item.CrCasRenterContractBasic5?.CrCasRenterLessorNavigation.CrMasRenterInformationArName
                    </td>
                }
                @{
                    // Calculate the total time span between the end date and now
                    var timeSpan = item.CrCasRenterContractBasicExpectedEndDate - DateTime.Now;

                    // Calculate the days, hours, and minutes difference
                    var daysNo = timeSpan?.Days ?? 0; // Ensure daysNo is not null
                    var hoursNo = timeSpan?.Hours ?? 0; // Ensure hoursNo is not null
                    var minutesNo = timeSpan?.Minutes ?? 0; // Ensure minutesNo is not null

                    // Determine the display value based on days, hours, and minutes
                    string displayValue;
                    string direction = "ltr"; // Default direction

                    if (daysNo < 0)
                    {
                        if (requestCulture?.RequestCulture.UICulture.Name != "ar-EG") displayValue = "Expired";
                        else
                        {
                            displayValue = "منتهي";
                            direction = "rtl"; // Set direction for Arabic
                        }
                    }
                    else if (daysNo == 0)
                    {
                        if (hoursNo < 1)
                        {
                            if (minutesNo <= 0)
                            {
                                if (requestCulture?.RequestCulture.UICulture.Name != "ar-EG") displayValue = "Expired";
                                else
                                {
                                    displayValue = "منتهي";
                                    direction = "rtl"; // Set direction for Arabic
                                }
                            }
                            else
                            {
                                if (requestCulture?.RequestCulture.UICulture.Name != "ar-EG")
                                {
                                    displayValue = $"{minutesNo} Minutes";
                                }
                                else
                                {
                                    displayValue = $"{minutesNo} دقيقة";
                                    direction = "rtl"; // Set direction for Arabic
                                }
                            }
                        }
                        else
                        {
                            if (requestCulture?.RequestCulture.UICulture.Name != "ar-EG")
                            {
                                displayValue = $"{hoursNo} Hours";
                            }
                            else
                            {
                                displayValue = $"{hoursNo} ساعة";
                                direction = "rtl"; // Set direction for Arabic
                            }
                        }
                    }
                    else
                    {
                        if (requestCulture?.RequestCulture.UICulture.Name != "ar-EG")
                        {
                            displayValue = $"{daysNo} Day";
                        }
                        else
                        {
                            displayValue = $"{daysNo} يوم";
                            direction = "rtl"; // Set direction for Arabic
                        }
                    }
                }
                <td onclick="location.href='@Url.Action("Create", "ContractSettlement", new { id = item.CrCasRenterContractBasicNo })'">
                    @displayValue
                </td>
                <td class="firstTable-col" onclick="location.href='@Url.Action("Create", "ContractSettlement", new { id = item.CrCasRenterContractBasicNo })'">
                    <div class="row flex-nowrap align-items-center">
                        <div class="col">
                            <p class="contract-id">
                                @item.CrCasRenterContractBasicNo
                                <span class="text-danger">
                                    @if (item.CrCasRenterContractBasicCopy > 0)
                                    {
                                        @item.CrCasRenterContractBasicCopy
                                    }
                                    @if (item.CrCasRenterContractBasicBranch != Model.SelectedBranch)
                                    {
                                        <span>*</span>
                                    }
                                </span>
                            </p>
                            <div class="row licence-dates-settel">
                                <div class="col-auto date-col">
                                    <div class="d-flex">
                                        <div class="col settelDate">@item.CrCasRenterContractBasicExpectedEndDate?.ToString("yyyy/MM/dd", CultureInfo.InvariantCulture)</div>
                                        <div class="col-auto p-0">@item.CrCasRenterContractBasicExpectedEndDate?.ToString("HH:mm", CultureInfo.InvariantCulture)</div>
                                    </div>
                                </div>
                                <div class="col-auto date-col">
                                    <div class="d-flex">
                                        <div class="col settelDate">@item.CrCasRenterContractBasicIssuedDate?.ToString("yyyy/MM/dd", CultureInfo.InvariantCulture)</div>
                                        <div class="col-auto p-0">@item.CrCasRenterContractBasicIssuedDate?.ToString("HH:mm", CultureInfo.InvariantCulture)</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </td>
                <td>
                    <div class="status-number gap-2">
                        @*                         <div class="status red-state"></div>
                    *@                        <div>@no</div>
                    </div>
                </td>
            </tr>
            no++;
        }

    </tbody>
</table>